spring:
  datasource:
    dynamic:
      primary: postgres  # 默认数据源（PostgreSQL）
      strict: false      # 非严格模式，允许未指定数据源时使用默认数据源
      datasource:
        # PostgreSQL 数据源配置
        postgres:
          driver-class-name: org.postgresql.Driver
          url: ${PG_URL}
          username: ${PG_USERNAME}
          password: ${PG_PASSWORD}
        # RisingWave 数据源配置（兼容PostgreSQL协议）
        risingwave:
          driver-class-name: org.postgresql.Driver
          url: ${RISINGWAVE_URL}
          username: ${RISINGWAVE_USERNAME}
          password: ${RISINGWAVE_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DB}
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: redis://${REDIS_HOST}:${REDIS_PORT}   
          database: ${REDIS_DB}
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
ckb:
  nodeUrl: https://testnet.ckb.dev
  netWork: 2 #
  default-hash-prefix: 0x
  default-with-prefix-hash-length: 66
  firstReleasedTimestampOther: 1593561600000
  secondReleasedTimestampOther: 1609372800000
  thirdReleasedTimestampOther: 1672444800000
  firstReleasedTimestampMay: 1588291200000
  secondReleasedTimestampMay: 1619827200000
  thirdReleasedTimestampMay: 1651363200000
statistic:
  averageBlockTimeInterval: 100
  hashRateStatisticalInterval: 900
script:
  lockScripts:
    - name: "SECP256K1/blake160"
      codeHash: "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
      hashType: "type"
    - name: "SECP256k1/Multisig(@5c5069eb)"
      codeHash: "0x5c5069eb0857efc65e1bca0c07df34c31663b3622fd3876c876320fc9634e2a8"
      hashType: "type"
    - name: "SECP256k1/Multisig(@36c971b8)"
      codeHash: "0x36c971b8d41fbd94aabca77dc75e826729ac98447b46f91e00796155dddb0d29"
      hashType: "data1"
    - name: "iCKB Logic"
      codeHash: "0x2a8100ab5990fa055ab1b50891702e1e895c7bd1df6322cd725c1a6115873bd3"
      hashType: "data1"
    - name: "AnyoneCanPay"
      codeHash: "0x3419a1c09eb2567f6552ee7a8ecffd64155cffe0f1796e6e61ec088d740c1356"
      hashType: "type"
    - name: "CHEQUE"
      codeHash: "0x60d5f39efce409c587cb9ea359cefdead650ca128f0bd9cb3855348f98c70d5b"
      hashType: "type"
    - name: "JoyId"
      codeHash: "0xd23761b364210735c19c60561d213fb3beae2fd6172743719eff6920e020baac"
      hashType: "type"
    - name: "OMNI Lock V2"
      codeHash: "0xf329effd1c475a2978453c8600e1eaf0bc2087ee093c3ee64cc96ec6847752cb"
      hashType: "type"
    - name: "OMNI Lock V1"
      codeHash: "0x79f90bb5e892d80dd213439eeab551120eb417678824f282b4ffb5f21bad2e1e"
      hashType: "type"
    - name: "PW Lock"
      codeHash: "0x58c5f491aba6d61678b7cf7edf4910b1f5e00ec0cde2f42e0abb4fd9aff25a63"
      hashType: "type"
    - name: "Nostr"
      codeHash: "0x6ae5ee0cb887b2df5a9a18137315b9bdc55be8d52637b2de0624092d5f0c91d5"
      hashType: "type"
    - name: "RgbppLock"
      codeHash: "0x61ca7a4796a4eb19ca4f0d065cb9b10ddcf002f10f7cbb810c706cb6bb5c3248"
      hashType: "type"
    - name: "BtcTimeLock"
      codeHash: "0x00cdf8fab0f8ac638758ebf5ea5e4052b1d71e8a77b9f43139718621f6849326"
      hashType: "type"
    - name: "AlwaysSuccess"
      codeHash: "0x3b521cc4b552f109d092d8cc468a8048acb53c5952dbe769d2b2f9cf6e47f7f1"
      hashType: "data1"
    - name: "InputTypeProxyLock"
      codeHash: "0x5123908965c711b0ffd8aec642f1ede329649bda1ebdca6bd24124d3796f768a"
      hashType: "data1"
    - name: "OutputTypeProxyLock"
      codeHash: "0x2df53b592db3ae3685b7787adcfef0332a611edb83ca3feca435809964c3aff2"
      hashType: "data1"
    - name: "LockProxyLock"
      codeHash: "0x5d41e32e224c15f152b7e6529100ebeac83b162f5f692a5365774dad2c1a1d02"
      hashType: "data1"
    - name: "Single Use Lock"
      codeHash: "0x8290467a512e5b9a6b816469b0edabba1f4ac474e28ffdd604c2a7c76446bbaf"
      hashType: "data1"
    - name: "TypeBurnLock"
      codeHash: "0xff78bae0abf17d7a404c0be0f9ad9c9185b3f88dcc60403453d5ba8e1f22f53a"
      hashType: "data1"
    - name: "TimeLock"
      codeHash: "0x6fac4b2e89360a1e692efcddcb3a28656d8446549fb83da6d896db8b714f4451"
      hashType: "data1"
  typeScripts:
    - name: "Nervos Dao"
      codeHash: "0x82d76d1b75fe2fd9a27dfbaa65a039221a380d76c926f378d3f81cf3e7e13f2e"
      hashType: "type"
      cellType: 1
    - name: "TypeId"
      codeHash: "0x00000000000000000000000000000000000000000000000000545950455f4944"
      hashType: "type"
    - name: "xUDT(final_rls)"
      codeHash: "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb"
      hashType: "type"
      cellType: 15
    - name: "USDI"
      codeHash: "0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037"
      hashType: "type"
      args: "0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f"
      cellType: 17
    - name: "RUSD"
      codeHash: "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a"
      hashType: "type"
      args: "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"
      cellType: 17
    - name: "tBtc"
      codeHash: "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb"
      hashType: "type"
      cellType: 15
      args: "0xe338fcbe878c4c656ac91b296882df9edc8b56cf00ae16acb4f0f49c09bccd02"
    - name: "BTCPP"
      codeHash: "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb"
      hashType: "type"
      args: "0x6d0cc2e3a8059f36dbee473e14b2b05d19a4d69f5bfd2a7abdc71fd32eece546"
      cellType: 15
    - name: "web5did"
      codeHash: "0x510150477b10d6ab551a509b71265f3164e9fd4137fcb5a4322f49f03092c7c5"
      hashType: "type"
    - name: "COTA"
      codeHash: "0x89cd8003a0eaf8e65e0c31525b7d1d5c1becefd2ea75bb4cff87810ae37764d8"
      hashType: "type"
      cellType: 10
    - name: "Unique Cell"
      codeHash: "0x8e341bcfec6393dcd41e635733ff2dca00a6af546949f70c57a706c0f344df8b"
      hashType: "type"
      cellType: 16
    - name: "EasyToDiscoverType"
      codeHash: "0xaba4430cc7110d699007095430a1faa72973edf2322ddbfd4d1d219cacf237af"
      hashType: "data1"
    - name: "spore_cluster_v1"
      codeHash: "0x598d793defef36e2eeba54a9b45130e4ca92822e1d193671f490950c3b856080"
      hashType: "data1"
      cellType: 11
      version: 1
    - name: "spore_cluster_v2"
      codeHash: "0x0bbe768b519d8ea7b96d58f1182eb7e6ef96c541fbd9526975077ee09f049058"
      hashType: "data1"
      cellType: 11
      version: 2
    - name: "spore_code_v1"
      codeHash: "0xbbad126377d45f90a8ee120da988a2d7332c78ba8fd679aab478a19d6c133494"
      hashType: "data1"
      cellType: 12
      version: 1
    - name: "spore_code_v2"
      codeHash: "0x685a60219309029d01310311dba953d67029170ca4848a4ff638e57002130a0d"
      hashType: "data1"
      cellType: 12
      version: 2
    - name: "BTC"
      codeHash: "0x98701eaf939113606a8a70013fd2e8f27b8f1e234acdc329f3d71f9e9d3d3233"
      hashType: "type"
      cellType: 17
    - name: "cusd"
      codeHash: "0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95"
      hashType: "data1"
      cellType: 15
    - name: "sudt"
      codeHash: "0x48dbf59b4c7ee1547238021b4869bceedf4eea6b43772e5d66ef8865b6ae7212"
      hashType: "data"
      cellType: 3
    - name: "sudt1"
      codeHash: "0xc5e5dcf215925f7ef4dfaf5f4b4f105bc321c02776d6e7d52a1db3fcd9d011a4"
      hashType: "type"
      cellType: 3
    - name: "did_cell"
      codeHash: "0x0b1f412fbae26853ff7d082d422c2bdd9e2ff94ee8aaec11240a5b34cc6e890f"
      hashType: "type"
      cellType: 18
