spring:
  application:
    name: ckb-explorer-web
  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/explorer
    username: ckb
    password: nervos
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 192.168.10.143
      port: 6350
      database: 4
