spring:
  application:
    name: ckb-explorer-worker
  profiles:
    active: testnet
  jackson:
    date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-handlers-package: com.ckb.explore.worker.config.mybatis
  configuration:
    map-underscore-to-camel-case: true